enum TextType {
  login,
  loginButton,
  pleaseEnterPhoneAndPass,
  // changeServerIp,
  // continuE,
  cancel,
  // dataSyncedDone,
  // hallsAndTabels,
  // confirm,
  // receipts,
  // groups,
  // setupConnection,
  // enterServerNumber,
  // request,
  // print,
  // enterTableId,
  // enterHallId,
  // noHalls,
  // noReceipts,
  // noTables,
  // noCategories,
  // noNotes,
  // noFood,
  // enterHallIdToShateTables,
  // theReceiptsTitle,
  // receiptNumber,
  // invoiceIsPending,
  // invoiceIsPreparing,
  // invoiceIsDone,
  // invoiceIsRequested,
  // invoiceIsPaid,
  // invoiceIsPrinted,
  // table,
  // captainId,
  // receiptTitle,
  // deleteInvoice,
  // receiptTableName,
  // theProcess,
  // theAmount,
  // thePrice,
  // theMaterialOrder,
  // totalPrice,
  // theNumber,
  // peicePrice,
  // receipt,
  // chooseHall,
  // theHall,
  // deviceIsTablet,
  // orderTitle,
  // paid,
  // unPaid,
  // choosedCustomer,
  // emptySearch,
  // finishAndLeave,
  // newOrder,
  // // ! dynamic texts from api
  // receiptNumberApi,
  // tableApi,
  // formattedInvoiceDateApi,
  // captainIdApi,
  // formattedInvoiceTimeApi,
  // categoryNameApi,
  // tableHallNameApi,
  // receiptTitleNumberApi,
  // tableNameApi,
  // receiptTableIdApi,
  // receiptOrderTotalApi,
  // categoriesListNameApi,
  // categoryNameAtBottomApi,
  // selectedHallApi,
  // orderNumberApi,
  // orderFoodNameApi,
  // orderFoodPriceApi,
  // orderFoodCountApi
}
